# shellcheck shell=bash
# =============================================================================
# 19-mta.sh — Lightweight local MTA (msmtp) for system mail delivery
# =============================================================================
#
# Configures a mail submission agent so anything that writes to sendmail
# actually reaches the operator's inbox: unattended-upgrades reports,
# cron job stdout/stderr, smartd / mdadm failure alerts, systemd OnFailure=
# units, apt-listchanges, and anything else that calls /usr/sbin/sendmail.
#
# msmtp-mta is a daemonless relay (upstream active; 1.8.32 shipped
# 2025-10-12). The -mta suffix is what matters: it registers via
# update-alternatives as /usr/sbin/sendmail, so every consumer picks it up
# without their own config. Nothing queues; transient network failures just
# fail loudly in /var/log/msmtp.log.
#
# A `root:` alias is added to /etc/aliases mapping to MTA_NOTIFY_EMAIL,
# which becomes the default for 29-unattended's UNATTENDED_MAIL prompt.
# =============================================================================

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${MODULE_DIR}/../lib.sh"
# shellcheck source=/dev/null
source "${MODULE_DIR}/../state.sh"

applies_mta() { return 0; }

# Existing-MTA detection: any active postfix/exim4 daemon, or a sendmail
# symlink pointing at something other than msmtp. On --redo of this module
# our own msmtp contains "msmtp" in the resolved path, so it's not flagged.
_mta_existing() {
    if systemctl is-active --quiet postfix 2>/dev/null; then
        echo "postfix"; return 0
    fi
    if systemctl is-active --quiet exim4 2>/dev/null; then
        echo "exim4"; return 0
    fi
    if [[ -L /usr/sbin/sendmail ]]; then
        local target
        target="$(readlink -f /usr/sbin/sendmail 2>/dev/null || true)"
        if [[ -n "$target" && "$target" != *msmtp* ]]; then
            echo "$target"; return 0
        fi
    fi
    return 1
}

detect_mta() {
    local existing
    if existing="$(_mta_existing)"; then
        state_set MTA_EXISTING "$existing"
    fi
}

configure_mta() {
    info "Lightweight SMTP relay (msmtp) so system mail reaches your inbox:"
    info "cron stdout, smartd/mdadm alerts, unattended-upgrades reports, etc."
    if ! ask_yesno "Configure a local MTA (msmtp)?" "n"; then
        state_mark_skipped mta
        return 0
    fi

    local existing
    existing="$(state_get MTA_EXISTING)"
    if [[ -n "$existing" ]]; then
        warn "Existing MTA detected (${existing}) — leaving it alone."
        state_mark_skipped mta
        return 0
    fi

    ask_input "Notification email (becomes /etc/aliases root:; default for later mail prompts)" \
        "$(state_get MTA_NOTIFY_EMAIL)"
    state_set MTA_NOTIFY_EMAIL "$REPLY"

    ask_input "SMTP relay host (e.g. smtp.gmail.com)" \
        "$(state_get MTA_HOST)"
    state_set MTA_HOST "$REPLY"

    ask_input "SMTP port (587 STARTTLS; 465 TLS-wrapped)" \
        "$(state_get MTA_PORT 587)" '^[0-9]+$'
    state_set MTA_PORT "$REPLY"

    ask_input "SMTP username (usually full email)" \
        "$(state_get MTA_USER)"
    state_set MTA_USER "$REPLY"

    ask_password "SMTP password (app password for Gmail/O365)" 1
    state_set MTA_PASSWORD "$REPLY"

    ask_input "From address (must match what the relay accepts)" \
        "$(state_get MTA_FROM "$(state_get MTA_USER)")"
    state_set MTA_FROM "$REPLY"
}

check_mta() {
    [[ -f /etc/msmtprc ]] \
        && [[ "$(stat -c %a /etc/msmtprc 2>/dev/null)" == "600" ]] \
        && command -v msmtp >/dev/null 2>&1
}

verify_mta() { check_mta; }

run_mta() {
    apt-get install -y -qq msmtp msmtp-mta mailutils 2>/dev/null

    local port tls_starttls
    port="$(state_get MTA_PORT)"
    # 465 = TLS-wrapped (tls_starttls off); 587 and anything else = STARTTLS.
    if [[ "$port" == "465" ]]; then tls_starttls="off"; else tls_starttls="on"; fi

    cat > /etc/msmtprc <<EOF
# Generated by modules/19-mta.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
defaults
auth           on
tls            on
tls_starttls   ${tls_starttls}
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        default
host           $(state_get MTA_HOST)
port           ${port}
from           $(state_get MTA_FROM)
user           $(state_get MTA_USER)
password       $(state_get MTA_PASSWORD)
EOF
    chmod 600 /etc/msmtprc
    chown root:root /etc/msmtprc

    touch /var/log/msmtp.log
    chmod 600 /var/log/msmtp.log

    # /etc/aliases: map root → operator so cron/timer mail also lands.
    # Match on ^root: so any existing alias (operator-managed or distro
    # default pointing at a local user) wins — we don't overwrite.
    local notify
    notify="$(state_get MTA_NOTIFY_EMAIL)"
    touch /etc/aliases
    if [[ -n "$notify" ]] && ! grep -qE "^root:" /etc/aliases; then
        printf 'root: %s\n' "$notify" >> /etc/aliases
    fi
    newaliases 2>/dev/null || true

    log "msmtp configured (host=$(state_get MTA_HOST):${port}, from=$(state_get MTA_FROM))"
    log "Test delivery:  echo test | mail -s 'wizard mta test' ${notify}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    require_root
    state_init
    detect_mta
    configure_mta
    state_skipped mta && exit 0
    run_mta
    verify_mta || { err "MTA verification failed"; exit 1; }
fi
