# shellcheck shell=bash
# =============================================================================
# 24-ssh-harden.sh — Harden sshd via drop-in config
# =============================================================================
#
# Writes /etc/ssh/sshd_config.d/99-hardening.conf. Validates with `sshd -t`
# before reloading the service — refuses to proceed if validation fails,
# rolling back the drop-in file so the previous (working) config stands.
#
# Pauses after reload so the operator can verify access from a second
# terminal; on "no", rolls back and exits. Load-bearing: removing this
# pause turns any sshd_config typo into a permanent lockout on a remote box.
# =============================================================================

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${MODULE_DIR}/../lib.sh"
# shellcheck source=/dev/null
source "${MODULE_DIR}/../state.sh"

SSH_HARDENING_FILE="/etc/ssh/sshd_config.d/99-hardening.conf"

applies_ssh_harden() { return 0; }

detect_ssh_harden() {
    [[ -n "$(state_get SSH_PORT)" ]] && return 0
    # Try to read a previously-applied port from the drop-in file.
    if [[ -f "$SSH_HARDENING_FILE" ]]; then
        local p
        p="$(awk '/^Port /{print $2; exit}' "$SSH_HARDENING_FILE" 2>/dev/null)"
        [[ -n "$p" ]] && state_set SSH_PORT "$p"
    fi
    [[ -z "$(state_get SSH_PORT)" ]] && state_set SSH_PORT "22"
}

configure_ssh_harden() {
    while true; do
        ask_input "SSH port (non-standard reduces bot noise)" "$(state_get SSH_PORT 22)" '^[0-9]+$'
        if validate_port "$REPLY"; then
            state_set SSH_PORT "$REPLY"
            break
        fi
        err "Invalid port: $REPLY"
    done
}

check_ssh_harden() {
    [[ -f "$SSH_HARDENING_FILE" ]] || return 1
    grep -q "^Port $(state_get SSH_PORT)\$" "$SSH_HARDENING_FILE"
}

run_ssh_harden() {
    detect_ssh_service || { err "Could not find SSH service"; exit 1; }

    local ssh_port user allow
    ssh_port="$(state_get SSH_PORT)"
    user="$(state_get USER_NAME)"
    allow=""
    [[ -n "$user" ]] && allow="AllowUsers ${user}"

    cat > "$SSH_HARDENING_FILE" <<EOF
# Generated by modules/24-ssh-harden.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Port ${ssh_port}
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
X11Forwarding no
MaxAuthTries 3
MaxSessions 3
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2
AllowTcpForwarding no
AllowAgentForwarding no
HostbasedAuthentication no
${allow}
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
EOF

    # Validate the full SSH configuration before reloading. If sshd -t fails
    # the daemon would refuse to restart, locking out the operator.
    local sshd_output
    if sshd_output=$(sshd -t 2>&1); then
        systemctl reload "$SSH_SERVICE"
        log "SSH hardened (key-only, no root, port ${ssh_port}) [service: ${SSH_SERVICE}]"
    else
        err "SSH config validation failed:"
        err "$sshd_output"
        rm -f "$SSH_HARDENING_FILE"
        exit 1
    fi

    # Safety net: operator must confirm access from another terminal.
    if [[ -n "$user" ]]; then
        echo ""
        warn "═══════════════════════════════════════════════════════════════"
        warn "  IMPORTANT: Do NOT close this terminal session!"
        warn "  Open a NEW terminal and verify SSH access:"
        warn "  ssh -p ${ssh_port} ${user}@<this-server-ip>"
        warn "═══════════════════════════════════════════════════════════════"
        echo ""
        if ! ask_yesno "Have you verified SSH access in another terminal?" "n"; then
            warn "Rolling back SSH hardening..."
            rm -f "$SSH_HARDENING_FILE"
            systemctl reload "$SSH_SERVICE"
            err "SSH hardening rolled back. Re-run after verifying access."
            exit 1
        fi
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    require_root
    state_init
    detect_ssh_harden
    configure_ssh_harden
    check_ssh_harden && { log "SSH already hardened with this port; skipping."; exit 0; }
    run_ssh_harden
fi
